# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colours.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import  QTimer
from PyQt5.QtGui import * 
from PyQt5.QtCore import * 
import random 
import sys 


class Ui_ColourWindow(object):
    def __init__(self): 
        super().__init__() 
        #self.setWindowTitle("Python ")  
        #self.setGeometry(100, 100, 500, 500) 
        self.setupUi(ColourWindow)    
        self.count_value = 30
        self.score_value = 0
        self.start_Flag = False
        self.Colour_list= ['Red', 'Blue', 'Green', 'Pink', 'Black', 
                   'Yellow', 'Orange', 'Purple', 'Brown','White']          
    
    
    
    def setupUi(self, ColourWindow):
        ColourWindow.setObjectName("ColourWindow")
        ColourWindow.resize(356, 468)
        self.centralwidget = QtWidgets.QWidget(ColourWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.greyzy_colour = QtWidgets.QLabel(self.centralwidget)
        self.greyzy_colour.setGeometry(QtCore.QRect(0, 0, 361, 421))
        self.greyzy_colour.setStyleSheet("background-Color: rgb(188, 54, 96);")
        self.greyzy_colour.setText("")
        self.greyzy_colour.setPixmap(QtGui.QPixmap("C:/Users/Sri Ramajayam/Desktop/UI/images/pp 1.jpg"))
        self.greyzy_colour.setScaledContents(True)
        self.greyzy_colour.setObjectName("greyzy_colour")
        self.instructions = QtWidgets.QLabel(self.centralwidget)
        self.instructions.setGeometry(QtCore.QRect(30, 80, 271, 20))
        self.instructions.setStyleSheet("font: 12pt \"Century\";\n"
"Color: rgb(255, 255, 255);")
        self.instructions.setObjectName("instructions")
        self.description1 = QtWidgets.QLabel(self.centralwidget)
        self.description1.setGeometry(QtCore.QRect(30, 90, 321, 31))
        self.description1.setStyleSheet("font: 12pt \"MV Boli\";\n"
"Color: rgb(255, 255, 255);")
        self.description1.setObjectName("description1")
        self.description2 = QtWidgets.QLabel(self.centralwidget)
        self.description2.setGeometry(QtCore.QRect(30, 110, 311, 21))
        self.description2.setStyleSheet("font: 12pt \"MV Boli\";\n"
"Color: rgb(255, 255, 255);")
        self.description2.setObjectName("description2")
        self.note = QtWidgets.QLabel(self.centralwidget)
        self.note.setGeometry(QtCore.QRect(0, 120, 281, 31))
        self.note.setStyleSheet("Color: rgb(255, 255, 255);\n"
"font: 10pt \"MV Boli\";")
        self.note.setObjectName("note")
        self.start_reset = QtWidgets.QPushButton(self.centralwidget)
        self.start_reset.setGeometry(QtCore.QRect(110, 160, 131, 31))
        self.start_reset.setStyleSheet("font: 11pt \"Century\";\n"
"background-Color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"Color: rgb(255, 255, 255);\n"
"")
        self.start_reset.setObjectName("start_reset")
        self.start_reset.clicked.connect(self.start_action)
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setGeometry(QtCore.QRect(100, 310, 171, 31))
        self.name_line.setStyleSheet("font: 14pt \"MV Boli\";")
        self.name_line.setText("")
        self.name_line.setObjectName("name_line")
        self.name_line.setDisabled(True)
        self.name_line.returnPressed.connect(self.input_action)
        self.Colour_name = QtWidgets.QLabel(self.centralwidget)
        self.Colour_name.setGeometry(QtCore.QRect(100, 260, 171, 31))
        self.Colour_name.setStyleSheet("font: 16pt \"Century\";\n"
"Color: rgb(255, 255, 255);")
        self.Colour_name.setObjectName("Colour_name") 
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 370, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("Color: rgb(255, 255, 255);\n"
"background-Color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.pushButton_2.setObjectName("pushButton_2") 
        self.colour_game = QtWidgets.QLabel(self.centralwidget)
        self.colour_game.setGeometry(QtCore.QRect(70, 30, 221, 31))
        self.colour_game.setStyleSheet("font: 18pt \"Lucida Calligraphy\";\n"
"Color: rgb(255, 255, 255);")
        self.colour_game.setObjectName("colour_game")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 210, 141, 31))
        self.label.setStyleSheet("font: 16pt \"Century\";\n"
"Color: rgb(255, 255, 255);\n"
";\n"
"background-Color: rgb(134, 15, 148);")
        self.label.setObjectName("label")
        ColourWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ColourWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 356, 21))
        self.menubar.setObjectName("menubar")
        ColourWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ColourWindow)
        self.statusbar.setObjectName("statusbar")
        ColourWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ColourWindow)
        QtCore.QMetaObject.connectSlotsByName(ColourWindow)

        self.timer = QtCore.QTimer() 
        self.timer.timeout.connect(self.show_time) 
        self.timer.start(1000)

    def retranslateUi(self, ColourWindow):
        _translate = QtCore.QCoreApplication.translate
        ColourWindow.setWindowTitle(_translate("ColourWindow", "MainWindow"))
        self.instructions.setText(_translate("ColourWindow", "INSTRUCTIONS:-"))
        self.description1.setText(_translate("ColourWindow", "Enter the colour not the text!! "))
        self.description2.setText(_translate("ColourWindow", "Press Start button to start the game"))
        self.note.setText(_translate("ColourWindow", "NOTE:-Time limit for game is 30 seconds"))
        self.start_reset.setText(_translate("ColourWindow", "START/RESET"))
        self.Colour_name.setText(_translate("ColourWindow", "COLOUR NAME"))
        self.pushButton_2.setText(_translate("ColourWindow", "30"))
        self.colour_game.setText(_translate("ColourWindow", "COLOUR GAME"))
        self.label.setText(_translate("ColourWindow", "    SCORE : 0"))
    def show_time(self): 
  
        if self.start_Flag:  
            self.pushButton_2.setText(str(self.count_value))  
            if self.count_value == 0:  
                self.start_Flag = False 
                self.name_line.setDisabled(True)  
            self.count_value -= 1
    def start_action(self):  
        self.start_Flag = True 
        self.label.setText("Score : 0") 
        self.score_value = 0 
        self.count_value = 30 
        self.name_line.clear()  
        self.name_line.setEnabled(True)  
        self.random_Colour = random.choice(self.Colour_list)  
        self.random_Colour.lower() 
        self.Colour_name.setStyleSheet("font: 16pt \"Century\";\n""Color : " + self.random_Colour + ";") 
        random_text = random.choice(self.Colour_list)  
        self.Colour_name.setText(random_text) 
  
  
  
    def input_action(self): 
  
         
        text = self.name_line.text()  
        text.lower() 
   
        if text == self.random_Colour:  
            self.name_line.clear()  
            self.score_value += 1
            self.label.setText("Score : " + str(self.score_value)) 
            self.random_Colour = random.choice(self.Colour_list)  
            self.random_Colour.lower()  
            self.Colour_name.setStyleSheet("font: 16pt \"Century\";\n""Color : " + self.random_Colour + ";")  
            random_text = random.choice(self.Colour_list) 
            self.Colour_name.setText(random_text) 
  
  

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ColourWindow = QtWidgets.QMainWindow()
    ui = Ui_ColourWindow()
    ui.setupUi(ColourWindow)
    ColourWindow.show()
    sys.exit(app.exec_())
